language: c++

compiler:  
      - gcc-5
      - clang

before_script:  
      - mkdir build
      - cd build
      - cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DLLVM_ENABLE_RTTI=ON -DLLVM_ENABLE_CXX1Y=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS_RELEASE="-O3" -G Ninja

script: ninja 
